apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds-logs-ingester-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rds-logs-ingester
  template:
    metadata:
      labels:
        app: rds-logs-ingester
    spec:
      containers:
      - name: rds-logs-ingester
        image: registry.devopsnow.io/private/opsverseinc/rds-logs-ingester:v1
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_REGION
        # Define other container specs as needed
      imagePullSecrets:
      - name: devopsnow-private-docker-reg-crd
